### ISSUE TITLE
容易发生panic

### ISSUE THREAD

**Issue by cloverzrg** [guanguans/id-validator#36]
```go
func Test02(t *testing.T) {
	t.Log(idvalidator.IsLooseValid("010-12345678转152"))
}
```

stack
```
--- FAIL: Test02 (0.00s)
panic: runtime error: index out of range [1] with length 0 [recovered]
	panic: runtime error: index out of range [1] with length 0

goroutine 8 [running]:
github.com/guanguans/id-validator.generateLongCode({0xd6f66c, 0x12})
	/home/xxx/go/pkg/mod/github.com/guanguans/id-validator@v1.2.8/checker.go:58 +0x385
github.com/guanguans/id-validator.generateCode({0xd6f66c?, 0xfb502c?})
	/home/xxx/go/pkg/mod/github.com/guanguans/id-validator@v1.2.8/checker.go:24 +0x31
github.com/guanguans/id-validator.IsValid({0xd6f66c?, 0x520a74?}, 0x0?)
	/home/xxx/go/pkg/mod/github.com/guanguans/id-validator@v1.2.8/id_validator.go:32 +0x26
github.com/guanguans/id-validator.IsLooseValid(...)
	/home/xx/go/pkg/mod/github.com/guanguans/id-validator@v1.2.8/id_validator.go:53
```

**Comment by cloverzrg** [comment]
版本 v1.2.8

**Comment by shuxiao9058** [comment]
@cloverzrg fix with pr #37
